services:
  frontend:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - backend-network
    command: npm run dev

networks:
  backend-network:
    driver: bridge
